applications:
  app:
    source:
      root: "/"
    type: "nginx:1.24"
    web:
      locations:
        "/":
          passthru: "http://simon.benbilal237free.xyz:80"

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
