applications:
  app:
    source:
      root: "/"
    type: "nginx:1.24"
    web:
      locations:
        "/":
          rules:
            proxy_pass: "http://simon.benbilal237free.xyz:80"
            proxy_set_header:
              Host: "simon.benbilal237free.xyz"
              X-Real-IP: "$remote_addr"
            proxy_http_version: "1.1"
            proxy_set_header_upgrade:
              Upgrade: "$http_upgrade"
              Connection: "upgrade"

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
